### ISSUE TITLE
V3 API: Spin up Hasura instance to expose data collected by dextick

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#62]
https://github.com/PeggyJV/dextick, our feeder, is going to populate a Cloud SQL Postgres database with necessary market data from both CoinGecko and Uniswap V2 (with a common data format).

We need to expose the contents of that PG DB in a way that is easily consumable by the app server. We've chosen to use GraphQL as a common language across all data sources, and https://hasura.io/ seems like a great solution for the use case - their product can expose a GraphQL wrapper for any Postgres DB.

We should use Hasura's [docker deployment](https://hasura.io/docs/latest/graphql/core/deployment/deployment-guides/docker.html#deployment-docker) for this work: we can then build it via Cloud Build and deploy it using Container Optimized OS for GCE (the same way we run the app).

**Prerequisites:**

1. Dextick data populated in some Cloud SQL Postgres (with known IP and auth creds). Should probably sync with @jackzampolin on when this can be available (at least some subset of data)

**Comment by tony-iqlusion** [comment]
As I mentioned on [this issue](https://github.com/PeggyJV/il-loss-charts/issues/46#issuecomment-813060620), this seems like a potentially interesting workload to deploy as a Cloud Function, as it's a stateless request/response-model service.

The main advantages of doing it that way are a simpler deployment (no need to maintain a Docker image) and simpler scalability.

The main disadvantage would be losing GraphQL subscriptions support (if we even care about that), however an interesting alternative there would be using Cloud SQL event triggers.

Cost is potentially something else to consider, although if we're really worried about that we should probably do some modeling.

Edit: after looking into Hasura (I'm not really familiar), and since there otherwise seems to be some consensus that this is the GraphQL server we want to use, it doesn't really seem to support this configuration (many other GraphQL servers do, although they're written in JS/TS and thus a better fit for Cloud Functions). So I guess Docker container it is...

**Comment by jackzampolin** [comment]
Closing as no longer necessary.
